Adding Spanish locale
SonarSoftwareInc/customer_portal pull request #184
Opened 2024-09-19 03:53 UTC by avative-pat

2024-10-27 18:18 UTC, avative-pat commented
Implements the following changes and improvements related to frontend languages:
1. Created directory lang/es and Spanish translated locale dictionaries.
2. Updated lang/en/languages.php and lang/fr/languages.php to add Spanish as a language option. 
3. Updated all language.php dictionaries to consistently display the language labels as the native language name, rather than displaying the translated name of each language. Example: When the portal is set to English language, the language selection now displays “Español” and “Français” as option labels, rather than “Spanish” and “French”. This makes the language selection experience more consistent and aids users when the default language is a language they are not fluent in and might have difficulty recognizing the language names when presented with translated labels.

2024-11-27 22:39 UTC, HellooooNewman requested changes
@avative-pat All these changes look good. We did find a few changes we might want but all of them are pretty small just a different way of saying it.

2024-11-27 22:39 UTC, HellooooNewman commented on lang/es/headers.php
> +    'myDetails' => 'Mis Detalles',
Mi Información

2024-11-27 22:39 UTC, HellooooNewman commented on lang/es/billing.php
> +    'expiration' => 'Expiración',
Vencimiento

2024-11-27 22:39 UTC, HellooooNewman commented on lang/es/nav.php
> +    'profile' => 'Mis Detalles',
Perfil

2024-11-27 22:39 UTC, HellooooNewman commented on lang/es/profile.php
> +    'changeYourDetails' => 'Cambiar tus detalles',
Cambiar tu Información

2024-11-27 22:39 UTC, HellooooNewman commented on lang/es/profile.php
> +    'updateDetails' => 'Actualizar Detalles',
Actualizar Información

2024-12-03 02:50 UTC, avative-pat reviewed
The suggested Spanish translation changes have been implemented

2025-02-03 15:42 UTC, HellooooNewman approved these changes

2025-02-03 15:42 UTC, merged